import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { fillTemplate } from "@/lib/templating";
import { generateTextPdf } from "@/lib/pdf";
import { getStorage, buildStorageKey } from "@/lib/storage";
import { sha256 } from "@/lib/crypto";
import { audit } from "@/lib/audit";
import { formatDate } from "@/lib/utils";

export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  const userId = (session.user as { id: string }).id;
  const { id } = await params;

  const r = await prisma.medicalRecordRequest.findUnique({
    where: { id },
    include: {
      claim: { include: { profile: { include: { user: true, teamHistory: true } } } },
    },
  });
  if (!r || r.claim.profile.user.id !== userId)
    return NextResponse.json({ error: "not found" }, { status: 404 });

  const tpl = await prisma.template.findFirst({
    where: {
      kind: r.providerType === "nfl_club" ? "hipaa_release_nfl_club" : "hipaa_release_third_party",
      isActive: true,
    },
  });
  if (!tpl) return NextResponse.json({ error: "no template" }, { status: 400 });

  const body = fillTemplate(tpl.body, {
    playerName: `${r.claim.profile.legalFirstName} ${r.claim.profile.legalLastName}`,
    dob: r.claim.profile.dateOfBirth.toLocaleDateString(),
    clubName: r.providerName,
    providerName: r.providerName,
    seasonYears: r.claim.profile.teamHistory
      .filter((t) => t.team.toLowerCase() === r.providerName.toLowerCase())
      .map((t) => `${t.startYear}–${t.endYear}`)
      .join(", ") || "—",
    recipientBlock: "Gridiron LOD\nc/o claimant",
    dateRangeStart: r.dateRangeStart ? formatDate(r.dateRangeStart) : "—",
    dateRangeEnd: r.dateRangeEnd ? formatDate(r.dateRangeEnd) : "—",
    expirationDate: formatDate(new Date(Date.now() + 1000 * 60 * 60 * 24 * 365)),
  });

  const pdfBytes = await generateTextPdf({
    title: tpl.name,
    sections: [{ body }],
    footer: `Generated by Gridiron LOD · ${new Date().toISOString()}`,
  });
  const buf = Buffer.from(pdfBytes);
  const storageKey = buildStorageKey({
    claimId: r.claimId,
    kind: "releases",
    filename: `release-${r.providerName.replace(/\W+/g, "_")}.pdf`,
  });
  await getStorage().put(storageKey, buf, "application/pdf");

  const doc = await prisma.document.create({
    data: {
      claimId: r.claimId,
      source: "player_upload",
      providerName: r.providerName,
      filename: `release-${r.providerName}.pdf`,
      mimeType: "application/pdf",
      byteSize: buf.byteLength,
      storageKey,
      sha256: sha256(buf),
      ocrStatus: "done",
      pageCount: 1,
    },
  });
  await prisma.medicalRecordRequest.update({
    where: { id },
    data: { releaseDocumentId: doc.id },
  });
  await audit({ userId, action: "records.release.generated", entityType: "records_request", entityId: id });

  return NextResponse.redirect(new URL(`/records/${id}`, process.env.NEXTAUTH_URL || "http://localhost:3000"));
}
